### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework-files#31] opened 2017-03-28 09:36 UTC
Some translations are reported missing. Seems that those displayed by the uploader aren't there.

See:

- https://support.joomlatools.com/forums/topic/7365

**Comment by ercanozkaya** [comment] 2017-03-31 12:46
@amazeika Closing this one as the problem is Docman not loading com:files translations. Moved into joomlatools/docman#1068

**Closed by ercanozkaya** 2017-03-31 12:46 UTC
Labels: bug
