### ISSUE TITLE
Drag and drop problem on Firefox

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-framework-files#35] opened 2017-05-12 21:37 UTC
See: https://support.joomlatools.com/forums/topic/7499-problem-with-drag-and-drop-in-firefox-53-0
See: https://support.joomlatools.com/forums/topic/7547-problem-with-drag-and-drop-in-firefox-53-0

Problem seems to be FF specific. I suggest to upgrade plupload to the latest 2.3.1 release, we are still on the older 2.1.9 release.

**Comment by waseemsadiq** [comment] 2017-09-04 11:19
Also see: https://support.joomlatools.com/tickets/topic/8041

**Comment by ercanozkaya** [comment] 2017-10-11 14:24
Duplicate of #33  Moved references, closing this one

**Closed by ercanozkaya** 2017-10-11 14:24 UTC
Labels: duplicate
